# Generated by Django 3.1.7 on 2021-04-20 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2021, 4, 20, 20, 1, 56, 673629))),
                ('end', models.DateTimeField(default=datetime.datetime(2021, 4, 20, 20, 1, 56, 673629))),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainings.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainings.exercisetitle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainings.training'),
        ),
    ]
