# Generated by Django 3.1.7 on 2021-04-14 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 13, 32, 53, 954989)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 13, 32, 53, 954989)),
        ),
    ]
