# Generated by Django 3.1.7 on 2021-04-20 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 20, 2, 54, 480221)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 20, 2, 54, 479223)),
        ),
    ]
