# Generated by Django 3.1.7 on 2021-04-06 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0002_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 16, 49, 58, 729186)),
        ),
    ]
