# Generated by Django 3.1.7 on 2021-04-19 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0003_auto_20210419_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainings.exercisetitle'),
        ),
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 17, 0, 18, 907647)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 17, 0, 18, 907647)),
        ),
    ]
