# Generated by Django 3.1.7 on 2021-04-06 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0003_auto_20210406_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='date',
        ),
        migrations.AddField(
            model_name='training',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 17, 31, 26, 96810)),
        ),
        migrations.AddField(
            model_name='training',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 17, 31, 26, 95811)),
        ),
    ]
