# Generated by Django 3.1.7 on 2021-04-06 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0004_auto_20210406_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 17, 38, 19, 989104)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 17, 38, 19, 989104)),
        ),
    ]
