# Generated by Django 3.1.7 on 2021-04-21 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0004_auto_20210421_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 17, 48, 29, 421778)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 17, 48, 29, 421778)),
        ),
    ]
