# Generated by Django 3.1.7 on 2021-04-20 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 20, 4, 26, 833842)),
        ),
    ]
