# Generated by Django 3.1.7 on 2021-04-21 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='statistictitle',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 18, 9, 22, 852787)),
        ),
    ]
