# Generated by Django 3.1.7 on 2021-04-21 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0002_auto_20210421_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 18, 11, 49, 671913)),
        ),
    ]
